/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_ccsd;

import java.awt.HeadlessException;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Dilip Pc
 */
public class Register extends javax.swing.JFrame {
    /**
     * Creates new form Register
     */
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    
    public Register() {
        initComponents();
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel20.setVisible(false);
        jLabel22.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(java.awt.Color.red);
        jLabel15.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automated Teller Machine - ABC Bank ");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ABC Bank");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLayeredPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setLabelFor(jLayeredPane1);
        jLabel2.setText("Name");
        jLabel2.setToolTipText("");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(100, 70, 60, 14);

        jTextField1.setToolTipText("Name ");
        jLayeredPane1.add(jTextField1);
        jTextField1.setBounds(170, 60, 160, 30);

        jTextField2.setText("dd/MM/yyyy");
        jTextField2.setToolTipText("Enter in dd/MM/yyyy format and age should be greater than 18");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jTextField2);
        jTextField2.setBounds(170, 340, 170, 30);

        jTextField3.setToolTipText("Mobile");
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jLayeredPane1.add(jTextField3);
        jTextField3.setBounds(170, 300, 170, 30);

        jLabel7.setText("Account Type");
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(60, 390, 100, 14);

        jLabel5.setText("DOB");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(100, 350, 60, 14);

        jLabel4.setText("Mobile");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(100, 310, 60, 14);

        jLabel3.setText("Email-Id");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(90, 110, 70, 14);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1);
        jButton1.setBounds(240, 530, 90, 23);

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton2);
        jButton2.setBounds(350, 530, 80, 23);

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel8.setText("Registration");
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(20, 30, 100, 20);

        jLabel6.setText("Confirm Password");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(40, 200, 120, 20);

        jLabel9.setText("Password");
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(80, 150, 80, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Savings", "Current" }));
        jLayeredPane1.add(jComboBox1);
        jComboBox1.setBounds(170, 390, 110, 20);

        jPasswordField1.setToolTipText("Password should contain minimum 8 characters");
        jLayeredPane1.add(jPasswordField1);
        jPasswordField1.setBounds(170, 150, 160, 30);

        jPasswordField2.setToolTipText("Confirm Password");
        jLayeredPane1.add(jPasswordField2);
        jPasswordField2.setBounds(170, 190, 160, 30);

        jLabel10.setText("Address");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(80, 250, 80, 14);

        jTextField4.setToolTipText("Email");
        jTextField4.setName(""); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jTextField4);
        jTextField4.setBounds(170, 100, 160, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(java.awt.Color.red);
        jLabel11.setText("jLabel11");
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(340, 100, 80, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(java.awt.Color.red);
        jLabel12.setText("jLabel12");
        jLayeredPane1.add(jLabel12);
        jLabel12.setBounds(350, 300, 80, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(java.awt.Color.red);
        jLabel13.setText("jLabel13");
        jLayeredPane1.add(jLabel13);
        jLabel13.setBounds(350, 340, 80, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(java.awt.Color.red);
        jLabel14.setText("jLabel14");
        jLayeredPane1.add(jLabel14);
        jLabel14.setBounds(340, 190, 80, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(java.awt.Color.red);
        jLabel16.setText("jLabel16");
        jLayeredPane1.add(jLabel16);
        jLabel16.setBounds(290, 380, 80, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(java.awt.Color.red);
        jLabel17.setText("jLabel11");
        jLayeredPane1.add(jLabel17);
        jLabel17.setBounds(340, 60, 80, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(java.awt.Color.red);
        jLabel18.setText("jLabel11");
        jLayeredPane1.add(jLabel18);
        jLabel18.setBounds(340, 150, 80, 30);

        jLabel19.setText("PIN");
        jLayeredPane1.add(jLabel19);
        jLabel19.setBounds(100, 490, 40, 14);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(java.awt.Color.red);
        jLabel20.setText("jLabel13");
        jLayeredPane1.add(jLabel20);
        jLabel20.setBounds(340, 480, 80, 30);

        jPasswordField3.setToolTipText("Confirm Password");
        jPasswordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField3KeyPressed(evt);
            }
        });
        jLayeredPane1.add(jPasswordField3);
        jPasswordField3.setBounds(170, 480, 160, 30);

        jLabel21.setText("A/C No");
        jLayeredPane1.add(jLabel21);
        jLabel21.setBounds(80, 440, 90, 14);

        jTextField5.setToolTipText("A/C Number 5 digits");
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jLayeredPane1.add(jTextField5);
        jTextField5.setBounds(170, 430, 160, 30);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea2.setName(""); // NOI18N
        jScrollPane2.setViewportView(jTextArea2);

        jLayeredPane1.add(jScrollPane2);
        jScrollPane2.setBounds(170, 236, 166, 50);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(java.awt.Color.red);
        jLabel22.setText("jLabel16");
        jLayeredPane1.add(jLabel22);
        jLabel22.setBounds(340, 430, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                String value1=jTextField1.getText();
                String value2=jTextField4.getText();
                String value4=jTextArea2.getText();
                String value3=jPasswordField1.getText();
                String value5=jTextField3.getText();
                String value6=jTextField2.getText();
                String value8=jComboBox1.getSelectedItem().toString();
                String value7=jPasswordField2.getText();
                String status="ACTIVE";
                java.util.Date time = Calendar.getInstance().getTime();
                int k=0,j=0;
                int b=1000;
                   int c=500;
                BufferedWriter bw = null;
       boolean mobval = Validation.isMobNo(jTextField3.getText());
       boolean acval = Validation.ac(jTextField5.getText());
       boolean emailval = Validation.validateEmail(jTextField4.getText());
       boolean dobval = Validation.isValidDate(jTextField2.getText());
       boolean pwdval = Validation.pswd(jPasswordField1.getText(), jPasswordField2.getText());
       int pwdlen=jPasswordField1.getText().length();
       int moblen=jTextField3.getText().length();
       int namval=jTextField1.getText().length();
       int pinval=jPasswordField3.getText().length();
       if (mobval==false || emailval==false || dobval==false || acval==false || pwdval==false || pwdlen<8 || moblen<10 || namval==0 || value8.equals("Select") || pinval>4 || pinval<4)
       { 
            if (mobval==false){
                jLabel12.setVisible(true);
                jLabel12.setText("*");
            }
             if (acval==false){
                jLabel22.setVisible(true);
                jLabel22.setText("*");
            }
            if (pinval>4 || pinval<4)
            {
                jLabel20.setVisible(true);
                jLabel20.setText("*");
            }
            if (value8.equals("Select"))
            {
                jLabel16.setVisible(true);
                jLabel16.setText("*");
            }
            if (namval==0){
                jLabel17.setVisible(true);
                jLabel17.setText("*");
            }
            if(pwdlen<8)
            {
              jLabel18.setVisible(true);
                jLabel18.setText("*");  
            }
             if(moblen<10)
            {
              jLabel12.setVisible(true);
              jLabel12.setText("*");  
            }
            if (pwdval==false){
                jLabel14.setVisible(true);
                jLabel14.setText("*");
            }
            if (dobval==false){
                jLabel13.setVisible(true);
                jLabel13.setText("*");
            }
            if (emailval==false){
                jLabel11.setVisible(true);
                jLabel11.setText("*");
            }
        }
       else {
          // jButton1.enable(true);
                try{
                 Class.forName("oracle.jdbc.driver.OracleDriver");
                 Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","CCSD","1234");
                 Statement st = con.createStatement();
                 k=st.executeUpdate("insert into CUST_DETAILS(name, email, password,address, mobile, dob, crdate) values('"+value1+"','"+value2+"','"+value3+"','"+value4+"','"+value5+"','"+value6+"','"+time.toString()+"')");
               String log=value2+" registered";
                 java.util.Date time1 = Calendar.getInstance().getTime();   
                 st.executeQuery("insert into LOG values('"+log+"','"+ time1.toString()+"')");
                 if (k==0)
                   JOptionPane.showMessageDialog(null,"Sorry, account cannot be created !!!");
                else {
             
  if (value8.equals("Savings")){
                st.executeQuery("insert into SBAL (accno,email,dep,bal,date1,abal) values('"+jTextField5.getText()+"','"+ value2+"','"+1000+"','"+1000+"','"+time.toString()+"','"+1000+"')");
                st.executeQuery("insert into SACCT (accno,email,status,pin) values('"+ jTextField5.getText()+"','"+ value2+"','"+ status +"','"+ Integer.parseInt(jPasswordField3.getText()) +"')"); 
                JOptionPane.showMessageDialog(null,"Account successfully created for "+value1.toUpperCase()+" \n Please login again with you email-id, password and account number");
                setVisible(false);
                 User u=new User(value2,b,time.toString());
                 u.setVisible(true);
                 u.setLocationRelativeTo(null);
  }
  else if (value8.equals("Current")){
                 st.executeQuery("insert into CBAL (accno,email,dep,bal,date1,abal) values('"+jTextField5.getText()+"','"+ value2+"','"+500+"','"+500+"','"+time.toString()+"','"+500+"')");
                 st.executeQuery("insert into CACCT (accno,email,status,pin) values('"+jTextField5.getText()+"','"+ value2+"','"+ status +"','"+ Integer.parseInt(jPasswordField3.getText()) +"')");setVisible(false);
                 JOptionPane.showMessageDialog(null,"Account successfully created for "+value1.toUpperCase()+" \n Please login again with you email-id, password and account number");
                 setVisible(false);
                 User u=new User(value2,c,time.toString());
                 u.setVisible(true);
                 u.setLocationRelativeTo(null);
  }
                  
  ResultSet rs = st.executeQuery("SELECT name,email,mobile,crdate from CUST_DETAILS");
                bw = new BufferedWriter(new FileWriter("AccountHolders.TXT"));
                StringBuilder  receipt = new StringBuilder();
                receipt.append("Name").append("       ").append("Email-ID").append("          ").append("Mobile").append("     ").append("Created On").append("       ");
                receipt.append("\n");
                while (rs.next()) {               
                receipt.append(rs.getString("name")).append("  ").append(rs.getString("email")).append("  ").append( rs.getString("mobile")).append("  ").append( rs.getString("crdate"));
        receipt.append("\n");
  }
  bw.write(receipt.toString());
  bw.flush();
  bw.newLine();
  
                }
        }catch(ClassNotFoundException | SQLException | HeadlessException | IOException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null,"Please register with an unique A/C Number");
            }
       } 
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("dd/MM/yyyy");
        jTextField3.setText("");
        jTextField4.setText("");
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel20.setVisible(false);
        jLabel22.setVisible(false);
        jTextArea2.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        jComboBox1.setSelectedIndex(0);
        jPasswordField3.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jPasswordField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField3KeyPressed
        // TODO add your handling code here:
        if(jPasswordField3.getText().length()>=4)
    
        jPasswordField3.setEditable(false);
    
         else 
             jPasswordField3.setEditable(true);
    }//GEN-LAST:event_jPasswordField3KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
         if(jTextField5.getText().length()>=5)
    
        jTextField5.setEditable(false);
    
         else 
             jTextField5.setEditable(true);
                       
    }//GEN-LAST:event_jTextField5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
Register r=new Register();
r.setVisible(true);
r.setLocationRelativeTo(null);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
