/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_ccsd;
import java.awt.HeadlessException;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.*;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Dilip Pc
 */
public class Transaction extends javax.swing.JFrame {

    /**
     * Creates new form Transaction
     */
    
    String val,an;
    int a,at;
     Deposit d1=new Deposit();
     Withdrawl w1=new Withdrawl();
     
     
    public Transaction() {
        initComponents();
        jTable2.setVisible(false);
    }
    
    public Transaction(String val,String an,int at)
    {
       initComponents();
        this.val=val;
        this.an=an;
        this.at=at;
        jLabel2.setText("Welcome "+val+" ["+an+"]");
        jLabel5.setVisible(false);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automated Teller Machine - ABC Bank ");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ABC Bank");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("jLabel2");

        jLabel3.setText("Withdraw");

        jButton1.setText("Submit");
        jButton1.setToolTipText("Withdrawl");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Deposit");

        jButton2.setText("Submit");
        jButton2.setToolTipText("Synchronized");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Print Mini Statement");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Withdrawls", "Deposit", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setEnabled(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel5.setText("jLabel5");

        jButton4.setText("Avail Balance");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setText("PIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jButton5.setText("Submit");
        jButton5.setToolTipText("Non-Synchronized");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Submit");
        jButton6.setToolTipText("Deadlock");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cancel / Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2))))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton6))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)
                            .addComponent(jButton2)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton7)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
  //String value1=jTextField1.getText();
        try{
                  Class.forName("oracle.jdbc.driver.OracleDriver");
                 Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "CCSD","1234");
                 if(at==1){
                 PreparedStatement pst = con.prepareStatement("SELECT date1,wd,dep,bal from SBAL where email='"+val+"' ORDER BY date1 DESC");
                 ResultSet rs=pst.executeQuery();
                 jTable2.setVisible(true);
                 jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                 }
                 else
                 {
                   PreparedStatement pst = con.prepareStatement("SELECT date1,wd,dep,bal from CBAL where email='"+val+"' ORDER BY date1 DESC");
                 ResultSet rs=pst.executeQuery();
                 jTable2.setVisible(true);
                 jTable2.setModel(DbUtils.resultSetToTableModel(rs));  
                 }
    }                                        
catch(  ClassNotFoundException | SQLException e){}
                       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        int d=Integer.parseInt(jTextField2.getText());
        int d2=Integer.parseInt(jTextField3.getText());
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
        
                 Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "CCSD","1234");
                 Statement st = con.createStatement();
               if (d%100==0 && d2%100==0){
                   JOptionPane.showConfirmDialog(null, "Do you want to continue ?");
        DepositThread dt=new DepositThread(d1,"Deposit1",d, val, an,at,jPasswordField1.getText());
        DepositThread dt1=new DepositThread(d1,"Deposit2",d2, val, an,at,jPasswordField1.getText());
        JOptionPane.showMessageDialog(null, "Deposit succesful !!! ");
        String log=val+" deposited Rs. "+d;
                     String log2=val+" deposited Rs. "+d2;
            java.util.Date time = Calendar.getInstance().getTime();   
            st.executeQuery("insert into LOG values('"+log+"','"+ time.toString()+"')");
            st.executeQuery("insert into LOG values('"+log2+"','"+ time.toString()+"')");
       try{
            dt.join();
            dt1.join();
        }
        catch(InterruptedException ex){
            System.out.println(ex+"error");
        }  
               }else
        {
            JOptionPane.showMessageDialog(null,"Please enter in multiples of 100","Error",JOptionPane.ERROR_MESSAGE);
            jTextField2.setText("");
            jTextField3.setText("");
        } 
        }catch(ClassNotFoundException | SQLException | HeadlessException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int w=Integer.parseInt(jTextField1.getText());
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
        
                 Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "CCSD","1234");
                 Statement st = con.createStatement();
        if (w%100==0){
            JOptionPane.showConfirmDialog(null, "Do you want to continue ?");
            WithdrawlThread wd1=new WithdrawlThread(w1,"Withdrwl",w, val, an,at,jPasswordField1.getText());
       JOptionPane.showMessageDialog(null, "Withdrawl succesful !!! ");
       String log=val+" withdrawn Rs. "+w;
            java.util.Date time = Calendar.getInstance().getTime();   
            st.executeQuery("insert into LOG values('"+log+"','"+ time.toString()+"')");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please enter in multiples of 100","Error",JOptionPane.ERROR_MESSAGE);
            jTextField1.setText("");
        }
        }catch(ClassNotFoundException | SQLException | HeadlessException e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int avb = 0; 
        try{
                 Class.forName("oracle.jdbc.driver.OracleDriver");
                 Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "CCSD","1234");
                 Statement st = con.createStatement();
                 if(at==1)
                 {
                 ResultSet rs=st.executeQuery("SELECT * from SBAL where email='"+val+"' and accno='"+an+"'");
                 while (rs.next()) {
                  avb=rs.getInt("abal");
                 }
                jLabel5.setText(Integer.toString(avb));
                    jLabel5.setVisible(true);
                    String log=val+" balance enquiry Rs. "+avb;
            java.util.Date time = Calendar.getInstance().getTime();   
            st.executeQuery("insert into LOG values('"+log+"','"+ time.toString()+"')");
                 }
                 else
                 {
                    ResultSet rs=st.executeQuery("SELECT * from CBAL where email='"+val+"' and accno='"+an+"'");
                 while (rs.next()) {
                  avb=rs.getInt("abal");
                 }
                jLabel5.setText(Integer.toString(avb));
                    jLabel5.setVisible(true); 
                    String log=val+" balance enquiry Rs. "+avb;
            java.util.Date time = Calendar.getInstance().getTime();   
            st.executeQuery("insert into LOG values('"+log+"','"+ time.toString()+"')");
                 }
         } catch(ClassNotFoundException | SQLException e)
                         {
                             System.out.println(e);
                         }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          int d=Integer.parseInt(jTextField2.getText());
        int d2=Integer.parseInt(jTextField3.getText());
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
        
                 Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "CCSD","1234");
                 Statement st = con.createStatement();
               if (d%100==0 && d2%100==0){
                   JOptionPane.showConfirmDialog(null, "Do you want to continue ?");
        DepositThread1 dt=new DepositThread1(d1,"Deposit1",d, val, an,at,jPasswordField1.getText());
        DepositThread1 dt1=new DepositThread1(d1,"Deposit2",d2, val, an,at,jPasswordField1.getText());
        
                     JOptionPane.showMessageDialog(null, "Deposit succesful !!! ");
                     String log=val+" deposited Rs. "+d;
                     String log2=val+" deposited Rs. "+d2;
            java.util.Date time = Calendar.getInstance().getTime();   
            st.executeQuery("insert into LOG values('"+log+"','"+ time.toString()+"')");
            st.executeQuery("insert into LOG values('"+log2+"','"+ time.toString()+"')");
               }else
        {
            JOptionPane.showMessageDialog(null,"Please enter in multiples of 100","Error",JOptionPane.ERROR_MESSAGE);
            jTextField2.setText("");
            jTextField3.setText("");
        }    
               } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
        
                 Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "CCSD","1234");
                 Statement st = con.createStatement();
                 String log=val+" logged out";
                 java.util.Date time = Calendar.getInstance().getTime();   
                 st.executeQuery("insert into LOG values('"+log+"','"+ time.toString()+"')");
        setVisible(false);
        User u=new User();
        u.setVisible(true);
        u.setLocationRelativeTo(null);
        ResultSet rs = st.executeQuery("SELECT * from LOG ORDER BY datetime DESC");
                BufferedWriter bw = new BufferedWriter(new FileWriter("Log.TXT"));
                StringBuilder  receipt = new StringBuilder();
                receipt.append("Detail").append("              ").append("Date/Time").append("          ");
                receipt.append("\n");
                while (rs.next()) {               
                receipt.append(rs.getString("details")).append("              ").append(rs.getString("datetime"));
        receipt.append("\n");
  }
  bw.write(receipt.toString());
  bw.flush();
  bw.newLine();
        }catch(ClassNotFoundException | SQLException e)
        {
            System.out.println(e);
        } catch (IOException ex) {
            Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int d=Integer.parseInt(jTextField2.getText());
        String pin2=jPasswordField1.getText();
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
        
                 Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "CCSD","1234");
                 Statement st = con.createStatement();
        int i;
  rwmonitor rw[ ]=new rwmonitor[2];
 
  for(i=0;i<1;i++)
   rw[i]=new rwmonitor(i,"balance",val,an,at);
  for(i=1;i<2;i++)
   rw[i]=new rwmonitor(i,"deposit",d,val,an,at,pin2); 
  for(i=1;i>=0;i--)
   rw[i].start();
            
                     String log=val+" deposited Rs. "+d;
                     
            java.util.Date time = Calendar.getInstance().getTime();   
            st.executeQuery("insert into LOG values('"+log+"','"+ time.toString()+"')");
           
        
        }catch(ClassNotFoundException | SQLException e){
            System.out.println(e);}
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
//               Transaction t = new Transaction();
////              
//   t.setVisible(true);
//
//
////                t.setLocationRelativeTo(null);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
